/*
 * This file is part of Dynamic Surroundings, licensed under the MIT License (MIT).
 *
 * Copyright (c) OreCruncher
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package org.orecruncher.dsurround.aurora;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.*;
import net.minecraft.client.renderer.GameRenderer;
import net.minecraft.util.Mth;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import org.joml.Matrix4f;

/**
 * Classic aurora implementation with vertical bands.
 * Uses simple geometry without shaders.
 */
@OnlyIn(Dist.CLIENT)
public class AuroraClassic extends AuroraBase {

    private static final int BAND_COUNT = 3;
    private static final double BAND_OFFSET = 150.0;
    private static final double SCALE_X = 0.5;
    private static final double SCALE_Y = 8.0;
    private static final double SCALE_Z = 0.5;

    private final AuroraBand band;
    private final int bandCount;
    private final double offset;

    public AuroraClassic(long seed) {
        super(seed);
        this.band = new AuroraBand(this.random);
        this.bandCount = BAND_COUNT;
        this.offset = BAND_OFFSET;

        // Now that all fields are initialized, generate geometry
        this.generateGeometry();
    }

    @Override
    protected void generateGeometry() {
        // Geometry is generated by AuroraBand
        this.band.generate();
    }

    @Override
    public void update() {
        super.update();
        this.band.update();
    }

    @Override
    public void render(PoseStack poseStack, float partialTick) {
        float alpha = getAlpha();
        if (alpha <= 0.0F) {
            return;
        }

        // Setup render state
        RenderSystem.enableBlend();
        RenderSystem.blendFuncSeparate(
                com.mojang.blaze3d.platform.GlStateManager.SourceFactor.SRC_ALPHA,
                com.mojang.blaze3d.platform.GlStateManager.DestFactor.ONE,
                com.mojang.blaze3d.platform.GlStateManager.SourceFactor.ONE,
                com.mojang.blaze3d.platform.GlStateManager.DestFactor.ZERO
        );
        RenderSystem.disableCull();
        RenderSystem.depthMask(false);
        RenderSystem.setShader(GameRenderer::getPositionColorShader);

        Tesselator tesselator = Tesselator.getInstance();
        BufferBuilder buffer = tesselator.getBuilder();

        Panel[] nodes = this.band.getNodes();

        for (int b = 0; b < this.bandCount; b++) {
            poseStack.pushPose();

            // Translate to follow player
            translate(poseStack);

            // Offset for multiple bands
            poseStack.translate(0, 0, this.offset * b);

            // Scale the aurora
            poseStack.scale((float) SCALE_X, (float) SCALE_Y, (float) SCALE_Z);

            Matrix4f matrix = poseStack.last().pose();

            buffer.begin(VertexFormat.Mode.TRIANGLES, DefaultVertexFormat.POSITION_COLOR);

            for (int i = 0; i < nodes.length - 1; i++) {
                Panel node = nodes[i];

                double posY = node.posY;
                double posX = node.tetX;
                double posZ = node.tetZ;
                double tetX = node.tetX2;
                double tetZ = node.tetZ2;

                double posX2;
                double posZ2;
                double tetX2;
                double tetZ2;
                double posY2;

                if (i < nodes.length - 2) {
                    Panel nodePlus = nodes[i + 1];
                    posX2 = nodePlus.tetX;
                    posZ2 = nodePlus.tetZ;
                    tetX2 = nodePlus.tetX2;
                    tetZ2 = nodePlus.tetZ2;
                    posY2 = nodePlus.posY;
                } else {
                    posX2 = tetX2 = node.posX;
                    posZ2 = tetZ2 = node.posZ;
                    posY2 = 0.0;
                }

                float baseR = this.topColor[0];
                float baseG = this.topColor[1];
                float baseB = this.topColor[2];
                float fadeR = this.bottomColor[0];
                float fadeG = this.bottomColor[1];
                float fadeB = this.bottomColor[2];

                // Front face
                buffer.vertex(matrix, (float) posX, 0.0F, (float) posZ).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) posX, (float) posY, (float) posZ).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) posX2, (float) posY2, (float) posZ2).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) posX2, (float) posY2, (float) posZ2).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) posX2, 0.0F, (float) posZ2).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) posX, 0.0F, (float) posZ).color(baseR, baseG, baseB, alpha).endVertex();

                // Bottom face
                buffer.vertex(matrix, (float) posX, 0.0F, (float) posZ).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) posX2, 0.0F, (float) posZ2).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) tetX2, 0.0F, (float) tetZ2).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) tetX2, 0.0F, (float) tetZ2).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) tetX, 0.0F, (float) tetZ).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) posX, 0.0F, (float) posZ).color(baseR, baseG, baseB, alpha).endVertex();

                // Back face
                buffer.vertex(matrix, (float) tetX, 0.0F, (float) tetZ).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) tetX, (float) posY, (float) tetZ).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) tetX2, (float) posY2, (float) tetZ2).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) tetX2, (float) posY2, (float) tetZ2).color(fadeR, fadeG, fadeB, 0.0F).endVertex();
                buffer.vertex(matrix, (float) tetX2, 0.0F, (float) tetZ2).color(baseR, baseG, baseB, alpha).endVertex();
                buffer.vertex(matrix, (float) tetX, 0.0F, (float) tetZ).color(baseR, baseG, baseB, alpha).endVertex();
            }

            tesselator.end();
            poseStack.popPose();
        }

        // Restore render state
        RenderSystem.depthMask(true);
        RenderSystem.enableCull();
        RenderSystem.defaultBlendFunc();
        RenderSystem.disableBlend();
    }

    @Override
    public String toString() {
        return "<CLASSIC> seed=" + this.seed + " alpha=" + getAlpha();
    }
}
